export enum ExtraComputation {
	TOLLS = 'TOLLS',
	FUEL_CONSUMPTION = 'FUEL_CONSUMPTION',
	TRAFFIC_ON_POLYLINE = 'TRAFFIC_ON_POLYLINE',
	HTML_FORMATTED_NAVIGATION_INSTRUCTIONS = 'HTML_FORMATTED_NAVIGATION_INSTRUCTIONS',
	FLYOVER_INFO_ON_POLYLINE = 'FLYOVER_INFO_ON_POLYLINE',
	NARROW_ROAD_INFO_ON_POLYLINE = 'NARROW_ROAD_INFO_ON_POLYLINE',
}
