export enum ExtraComputation {
	// EXTRA_COMPUTATION_UNSPECIFIED = 0,
	TOLLS = 1,
	FUEL_CONSUMPTION = 2,
	TRAFFIC_ON_POLYLINE = 3,
	HTML_FORMATTED_NAVIGATION_INSTRUCTIONS = 4,
	// FLYOVER_INFO_ON_POLYLINE = 7,
	// NARROW_ROAD_INFO_ON_POLYLINE = 8,
}
