export enum RouteLabel {
	ROUTE_LABEL_UNSPECIFIED = 'ROUTE_LABEL_UNSPECIFIED',
	DEFAULT_ROUTE = 'DEFAULT_ROUTE',
	DEFAULT_ROUTE_ALTERNATE = 'DEFAULT_ROUTE_ALTERNATE',
	FUEL_EFFICIENT = 'FUEL_EFFICIENT',
	SHORTER_DISTANCE = 'SHORTER_DISTANCE',
}
