export enum VehicleEmissionType {
	// VEHICLE_EMISSION_TYPE_UNSPECIFIED = 'VEHICLE_EMISSION_TYPE_UNSPECIFIED',
	GASOLINE = 'GASOLINE',
	ELECTRIC = 'ELECTRIC',
	HYBRID = 'HYBRID',
	DIESEL = 'DIESEL',
}
